databases:
  - name: newslizer
    databaseName: rails_articles_analizer_production
    user: rails_articles_analizer

services:
  - type: web
    name: newslizer
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newslizer
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
